# Generated by Django 4.0.9 on 2024-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter your email address.', max_length=256, unique=True, verbose_name='email address'),
        ),
    ]
