# Generated by Django 4.2.9 on 2024-01-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_verify_user_is_verify_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verify_email',
            new_name='is_verified_email',
        ),
    ]
